<script src="{{ asset('front-end') }}/assets/js/jquery.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/popper.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/bootstrap.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/bootstrap-select.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/wow.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/counterup.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/scroll-up-bar.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/jquery.fancybox.min.js"></script>
{{-- <script src="{{ asset('front-end') }}/assets/js/perfect-scrollbar.min.js"></script> --}}
<script src="{{ asset('front-end') }}/assets/js/styleswitcher.js"></script>
<script src="{{ asset('front-end') }}/assets/js/slick.min.js"></script>
<script src="{{ asset('front-end') }}/assets/js/custom-scripts.js"></script>
